export const AuditAction = {
    APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",

    COMPANY_MEMBER_ADDED: "COMPANY_MEMBER_ADDED",
    COMPANY_MEMBER_ROLE_CHANGED: "COMPANY_MEMBER_ROLE_CHANGED",
    COMPANY_MEMBER_REMOVED: "COMPANY_MEMBER_REMOVED",
    COMPANY_OWNERSHIP_TRANSFERRED: "COMPANY_OWNERSHIP_TRANSFERRED",
    COMPANY_INVITATION_SENT: "COMPANY_INVITATION_SENT",
    COMPANY_INVITATION_RESENT: "COMPANY_INVITATION_RESENT",
    COMPANY_INVITATION_CANCELLED: "COMPANY_INVITATION_CANCELLED",
    COMPANY_INVITATION_ACCEPTED: "COMPANY_INVITATION_ACCEPTED",

    JOB_CREATED: "JOB_CREATED",
    JOB_UPDATED: "JOB_UPDATED",
    JOB_PUBLISHED: "JOB_PUBLISHED",
    JOB_PAUSED: "JOB_PAUSED",
    JOB_ARCHIVED: "JOB_ARCHIVED",
    JOB_RESTORED: "JOB_RESTORED",
    JOB_RENEWED: "JOB_RENEWED",
    JOB_DELETED: "JOB_DELETED",

    COMPANY_CREATED: "COMPANY_CREATED",
    COMPANY_PROFILE_UPDATED: "COMPANY_PROFILE_UPDATED",
    COMPANY_LOGO_UPDATED: "COMPANY_LOGO_UPDATED",
    COMPANY_LOGO_REMOVED: "COMPANY_LOGO_REMOVED",
    COMPANY_BANNER_UPDATED: "COMPANY_BANNER_UPDATED",
    COMPANY_BANNER_REMOVED: "COMPANY_BANNER_REMOVED",
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
    APPLICATION: "APPLICATION",
    COMPANY_MEMBERSHIP: "COMPANY_MEMBERSHIP",
    COMPANY_INVITATION: "COMPANY_INVITATION",
    JOB: "JOB",
    COMPANY: "COMPANY",
} as const;

export type AuditEntityTypeValue = (typeof AuditEntityType)[keyof typeof AuditEntityType];
