export const NOTIFICATION_TYPES = {
    SYSTEM: "SYSTEM",
    APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
    APPLICATION_FIRST_VIEWED: "APPLICATION_FIRST_VIEWED",
    APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",
    APPLICATION_WITHDRAWN: "APPLICATION_WITHDRAWN",
    NEW_APPLICATION: "NEW_APPLICATION",
    COMPANY_INVITATION_ACCEPTED: "COMPANY_INVITATION_ACCEPTED",
    COMPANY_SUSPENDED: "COMPANY_SUSPENDED",
    COMPANY_RESTORED: "COMPANY_RESTORED",
    JOB_EXPIRING: "JOB_EXPIRING",
    JOB_EXPIRED: "JOB_EXPIRED",
    JOB_MODERATED: "JOB_MODERATED",
    ADMIN_REVIEW_REQUIRED: "ADMIN_REVIEW_REQUIRED",
    JOB_REPORT_UPDATED: "JOB_REPORT_UPDATED",
} as const;

export const NOTIFICATION_ENTITY_TYPES = {
    APPLICATION: "APPLICATION",
    COMPANY: "COMPANY",
    COMPANY_INVITATION: "COMPANY_INVITATION",
    JOB: "JOB",
    USER: "USER",
    JOB_REPORT: "JOB_REPORT",
} as const;
