export const PLATFORM_ADMIN_ACTIONS = {
    USER_SUSPENDED: "USER_SUSPENDED",
    USER_RESTORED: "USER_RESTORED",
    COMPANY_VERIFIED: "COMPANY_VERIFIED",
    COMPANY_UNVERIFIED: "COMPANY_UNVERIFIED",
    COMPANY_SUSPENDED: "COMPANY_SUSPENDED",
    COMPANY_RESTORED: "COMPANY_RESTORED",
} as const;

export const PLATFORM_ADMIN_ENTITY_TYPES = {
    USER: "USER",
    COMPANY: "COMPANY",
    JOB: "JOB",
    JOB_CATEGORY: "JOB_CATEGORY",
    JOB_REPORT: "JOB_REPORT",
} as const;

export type PlatformAdminAction =
    (typeof PLATFORM_ADMIN_ACTIONS)[keyof typeof PLATFORM_ADMIN_ACTIONS];

export type PlatformAdminEntityType =
    (typeof PLATFORM_ADMIN_ENTITY_TYPES)[keyof typeof PLATFORM_ADMIN_ENTITY_TYPES];
